#!/bin/bash

echo "🔐 GitHub Secrets Quick Setup Guide"
echo "===================================="
echo ""
echo "Repository: https://github.com/vishaal314/dataguardian-pro"
echo ""
echo "STEP 1: Access GitHub Secrets"
echo "-----------------------------"
echo "1. Go to: https://github.com/vishaal314/dataguardian-pro/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo ""

echo "STEP 2: Add Required Secrets"
echo "----------------------------"
echo ""
echo "🖥️ SERVER CONNECTION SECRETS:"
echo "----------------------------"
echo ""
echo "Secret Name: SERVER_HOST"
echo "Value: your-server-ip-or-domain.com"
echo "Example: 159.89.123.45 or dataguardianpro.nl"
echo ""
echo "Secret Name: SERVER_USER"  
echo "Value: ubuntu"
echo "Note: Or whatever user you use to SSH into your server"
echo ""
echo "Secret Name: SERVER_PATH"
echo "Value: /opt/dataguardian-pro"
echo "Note: Where the app will be deployed on your server"
echo ""
echo "Secret Name: SERVER_SSH_KEY"
echo "Value: [Your private SSH key content]"
echo "Note: Generate with: ssh-keygen -t rsa -b 4096 -f ~/.ssh/dataguardian_deploy"
echo "      Then copy content of private key file"
echo ""

echo "🔑 APPLICATION SECRETS:"
echo "----------------------"
echo ""
echo "Secret Name: OPENAI_API_KEY"
echo "Value: sk-..."
echo "Note: Your OpenAI API key (if you have one)"
echo ""
echo "Secret Name: STRIPE_SECRET_KEY"  
echo "Value: sk_live_..."
echo "Note: Your Stripe secret key (if you have one)"
echo ""

echo "STEP 3: Generate SSH Key (If Needed)"
echo "------------------------------------"
echo ""
echo "On your local machine or server:"
echo ""
echo "# Generate SSH key pair"
echo "ssh-keygen -t rsa -b 4096 -f ~/.ssh/dataguardian_deploy"
echo ""
echo "# Add public key to your server"
echo "ssh-copy-id -i ~/.ssh/dataguardian_deploy.pub user@your-server.com"
echo ""
echo "# Copy private key content for GitHub secret"
echo "cat ~/.ssh/dataguardian_deploy"
echo ""

echo "STEP 4: Prepare Your Production Server"
echo "-------------------------------------"
echo ""
echo "Run these commands on your production server:"
echo ""
echo "# Update system and install Python"
echo "sudo apt update && sudo apt install -y python3 python3-pip python3-venv nginx"
echo ""
echo "# Create deployment directory"
echo "sudo mkdir -p /opt/dataguardian-pro"
echo "sudo chown \$USER:\$USER /opt/dataguardian-pro"
echo ""
echo "# Set up firewall"
echo "sudo ufw allow 22   # SSH"
echo "sudo ufw allow 80   # HTTP"
echo "sudo ufw allow 443  # HTTPS"  
echo "sudo ufw enable"
echo ""

echo "STEP 5: Test Server Connection"
echo "------------------------------"
echo ""
echo "Test SSH connection:"
echo "ssh -i ~/.ssh/dataguardian_deploy user@your-server.com"
echo ""
echo "If successful, you're ready for deployment!"
echo ""

echo "🎯 QUICK CHECKLIST"
echo "=================="
echo ""
echo "GitHub Secrets to Add:"
echo "□ SERVER_HOST"
echo "□ SERVER_USER" 
echo "□ SERVER_PATH"
echo "□ SERVER_SSH_KEY"
echo "□ OPENAI_API_KEY (optional)"
echo "□ STRIPE_SECRET_KEY (optional)"
echo ""
echo "Server Preparation:"
echo "□ Python 3 installed"
echo "□ SSH access configured"
echo "□ Deployment directory created"
echo "□ Firewall configured"
echo ""
echo "🚀 Once secrets are added and server is ready:"
echo "   Push code to GitHub → Actions run → Production deploy!"
echo ""
echo "Settings URL: https://github.com/vishaal314/dataguardian-pro/settings/secrets/actions"