#!/bin/bash
#
# ┌─────────────────────────────────────────────────────────────────┐
# │ STANDALONE PRODUCTION FIX - dataguardianpro.nl                 │
# │                                                                 │
# │ Fixes: 1) Blob Scan removal (16 scanners only)                 │
# │        2) STRIPE_SECRET_KEY environment error                  │
# │                                                                 │
# │ Usage: Just copy this file and run it. No dependencies.        │
# │                                                                 │
# │ Quick run:                                                      │
# │   wget https://your-server/STANDALONE_FIX.sh                   │
# │   chmod +x STANDALONE_FIX.sh                                   │
# │   ./STANDALONE_FIX.sh                                          │
# │                                                                 │
# │ Or one-liner:                                                   │
# │   curl -sSL your-url/STANDALONE_FIX.sh | bash                  │
# └─────────────────────────────────────────────────────────────────┘
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

clear

echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║         ${BOLD}STANDALONE PRODUCTION FIX${NC}${CYAN}                           ║${NC}"
echo -e "${CYAN}║         dataguardianpro.nl                                     ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Verify we're in the right location
if [ ! -d "/opt/dataguardian" ]; then
    echo -e "${RED}❌ ERROR: /opt/dataguardian not found${NC}"
    echo ""
    echo "This script must be run on the production server."
    echo "Please SSH to root@dataguardianpro.nl first."
    exit 1
fi

cd /opt/dataguardian
echo -e "${GREEN}✅ Location verified: $(pwd)${NC}"
echo ""

#═══════════════════════════════════════════════════════════════════
# PHASE 1: ENVIRONMENT SETUP
#═══════════════════════════════════════════════════════════════════
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}${BOLD} PHASE 1: Environment Configuration${NC}"
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

ENV_FILE="/root/.dataguardian_env"

# Create environment file if missing
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  Environment file not found. Creating template...${NC}"
    
    cat > "$ENV_FILE" << 'ENVEOF'
# DataGuardian Pro Production Environment
# Generated by STANDALONE_FIX.sh

# === REQUIRED: Stripe Payment Processing ===
STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=

# === REQUIRED: OpenAI for AI Analysis ===
OPENAI_API_KEY=

# === Security Keys (Auto-generated if empty) ===
DATAGUARDIAN_MASTER_KEY=
JWT_SECRET=

# === Database ===
DATABASE_URL=postgresql://dataguardian:your_password@postgres:5432/dataguardian

# === Application Settings ===
PYTHONUNBUFFERED=1
STREAMLIT_SERVER_PORT=5000
STREAMLIT_SERVER_ADDRESS=0.0.0.0
STREAMLIT_SERVER_HEADLESS=true

# === Multi-tenant ===
DISABLE_RLS=true
ENVEOF
    
    chmod 600 "$ENV_FILE"
    
    echo -e "${RED}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${RED}║  ${BOLD}⚠️  ACTION REQUIRED: Configure API Keys${NC}${RED}                    ║${NC}"
    echo -e "${RED}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Template created at: $ENV_FILE"
    echo ""
    echo "You MUST add your API keys before continuing:"
    echo ""
    echo -e "${YELLOW}  nano $ENV_FILE${NC}"
    echo ""
    echo "Required keys:"
    echo "  • STRIPE_SECRET_KEY=sk_test_...  (Get from stripe.com/dashboard)"
    echo "  • OPENAI_API_KEY=sk-...          (Get from platform.openai.com)"
    echo ""
    echo "After saving, run this script again:"
    echo -e "${CYAN}  ./STANDALONE_FIX.sh${NC}"
    echo ""
    exit 1
fi

# Load environment
source "$ENV_FILE"

# Validate STRIPE_SECRET_KEY
if [ -z "$STRIPE_SECRET_KEY" ]; then
    echo -e "${RED}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${RED}║  ${BOLD}❌ ERROR: STRIPE_SECRET_KEY Not Set${NC}${RED}                        ║${NC}"
    echo -e "${RED}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Edit the environment file:"
    echo -e "${YELLOW}  nano $ENV_FILE${NC}"
    echo ""
    echo "Add this line (replace with your actual key):"
    echo -e "${CYAN}  STRIPE_SECRET_KEY=sk_test_YOUR_KEY_HERE${NC}"
    echo ""
    echo "Get your key: https://dashboard.stripe.com/test/apikeys"
    echo ""
    echo "Then run this script again."
    echo ""
    exit 1
else
    echo -e "${GREEN}✅ STRIPE_SECRET_KEY configured (${STRIPE_SECRET_KEY:0:12}...)${NC}"
fi

# Check OPENAI_API_KEY
if [ -z "$OPENAI_API_KEY" ]; then
    echo -e "${YELLOW}⚠️  OPENAI_API_KEY not set (AI features disabled)${NC}"
else
    echo -e "${GREEN}✅ OPENAI_API_KEY configured (${OPENAI_API_KEY:0:12}...)${NC}"
fi

echo ""

#═══════════════════════════════════════════════════════════════════
# PHASE 2: BLOB SCAN REMOVAL
#═══════════════════════════════════════════════════════════════════
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}${BOLD} PHASE 2: Remove Blob Scan (Target: 16 Scanners)${NC}"
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "🔧 Fixing services/stripe_payment.py..."

python3 << 'ENDPYTHON1'
# Fix stripe_payment.py - Remove Blob Scan, keep 16 scanners
with open('services/stripe_payment.py', 'r') as f:
    lines = f.readlines()

new_lines = []
skip_mode = None

for line in lines:
    if 'SCAN_PRICES = {' in line or 'SCAN_PRICES={' in line:
        skip_mode = 'SCAN_PRICES'
        new_lines.extend([
            '# Pricing for each scan type (in cents EUR)\n',
            'SCAN_PRICES = {\n',
            '    # Basic Scanners (7)\n',
            '    "Manual Upload": 900,\n',
            '    "API Scan": 1800,\n',
            '    "Code Scan": 2300,\n',
            '    "Image Scan": 2800,\n',
            '    "Database Scan": 4600,\n',
            '    "Website Scan": 2500,\n',
            '    "DPIA Scan": 3800,\n',
            '    \n',
            '    # Advanced Scanners (3)\n',
            '    "Sustainability Scan": 3200,\n',
            '    "AI Model Scan": 4100,\n',
            '    "SOC2 Scan": 5500,\n',
            '    \n',
            '    # Enterprise Connectors (6)\n',
            '    "Google Workspace Scan": 6800,\n',
            '    "Microsoft 365 Scan": 7500,\n',
            '    "Enterprise Scan": 8900,\n',
            '    "Salesforce Scan": 9200,\n',
            '    "Exact Online Scan": 12500,\n',
            '    "SAP Integration Scan": 15000,\n',
            '}\n'
        ])
        continue
    elif 'SCAN_PRODUCTS = {' in line or 'SCAN_PRODUCTS={' in line:
        skip_mode = 'SCAN_PRODUCTS'
        new_lines.extend([
            '\n# Product names for each scan type\n',
            'SCAN_PRODUCTS = {\n',
            '    "Manual Upload": "DataGuardian Pro Manual Upload Scanner",\n',
            '    "API Scan": "DataGuardian Pro API Scanner",\n',
            '    "Code Scan": "DataGuardian Pro Code Scanner",\n',
            '    "Image Scan": "DataGuardian Pro Image Scanner",\n',
            '    "Database Scan": "DataGuardian Pro Database Scanner",\n',
            '    "Website Scan": "DataGuardian Pro Website Scanner",\n',
            '    "DPIA Scan": "DataGuardian Pro DPIA Assessment",\n',
            '    "Sustainability Scan": "DataGuardian Pro Sustainability Scanner",\n',
            '    "AI Model Scan": "DataGuardian Pro AI Model Scanner",\n',
            '    "SOC2 Scan": "DataGuardian Pro SOC2 Scanner",\n',
            '    "Google Workspace Scan": "DataGuardian Pro Google Workspace Scanner",\n',
            '    "Microsoft 365 Scan": "DataGuardian Pro Microsoft 365 Scanner",\n',
            '    "Enterprise Scan": "DataGuardian Pro Enterprise Scanner",\n',
            '    "Salesforce Scan": "DataGuardian Pro Salesforce Scanner",\n',
            '    "Exact Online Scan": "DataGuardian Pro Exact Online Connector",\n',
            '    "SAP Integration Scan": "DataGuardian Pro SAP Integration Scanner",\n',
            '}\n'
        ])
        continue
    elif 'SCAN_DESCRIPTIONS = {' in line or 'SCAN_DESCRIPTIONS={' in line:
        skip_mode = 'SCAN_DESCRIPTIONS'
        new_lines.extend([
            '\n# Descriptions for each scan type\n',
            'SCAN_DESCRIPTIONS = {\n',
            '    "Manual Upload": "Manual file scanning for PII detection",\n',
            '    "API Scan": "API scanning for data exposure and compliance issues",\n',
            '    "Code Scan": "Comprehensive code scanning for PII and secrets detection",\n',
            '    "Image Scan": "Image scanning for faces and visual identifiers",\n',
            '    "Database Scan": "Database scanning for GDPR compliance",\n',
            '    "Website Scan": "Website scanning for cookies, trackers, and privacy policy compliance",\n',
            '    "DPIA Scan": "Data Protection Impact Assessment for GDPR Article 35 compliance",\n',
            '    "Sustainability Scan": "Cloud resource optimization and sustainability analysis",\n',
            '    "AI Model Scan": "AI model auditing for bias and GDPR compliance",\n',
            '    "SOC2 Scan": "SOC2 security and access control auditing",\n',
            '    "Google Workspace Scan": "Google Workspace organization scanning for data exposure",\n',
            '    "Microsoft 365 Scan": "Microsoft 365 tenant scanning for PII and compliance issues",\n',
            '    "Enterprise Scan": "Advanced enterprise data scanning with full connector suite",\n',
            '    "Salesforce Scan": "Salesforce CRM data scanning for customer privacy compliance",\n',
            '    "Exact Online Scan": "Direct integration scanning for Exact Online accounting data",\n',
            '    "SAP Integration Scan": "SAP ERP system integration with GDPR compliance analysis",\n',
            '}\n'
        ])
        continue
    elif skip_mode and line.strip() == '}':
        skip_mode = None
        continue
    elif skip_mode:
        continue
    else:
        new_lines.append(line)

with open('services/stripe_payment.py', 'w') as f:
    f.writelines(new_lines)

print("✅ stripe_payment.py updated (16 scanners)")
ENDPYTHON1

echo "🔧 Removing ALL blob references from app.py..."

python3 << 'ENDPYTHON2'
import re

# Remove all blob references from app.py
with open('app.py', 'r') as f:
    lines = f.readlines()

new_lines = []

for line in lines:
    # Skip lines with blob references
    if any([
        'ScannerType.BLOB' in line,
        "_('scan.blob'" in line,
        '_("scan.blob"' in line,
        '"Blob Scan"' in line,
        "'Blob Scan'" in line,
        ("'blob':" in line or '"blob":' in line) and ('Scanner' in line or '📄' in line),
        'from services.blob_scanner import' in line,
        'BlobScanner(' in line,
        ('elif' in line and 'blob' in line.lower() and ('Document' in line or 'Scanner' in line)),
        ('f"📄' in line and 'blob' in line.lower())
    ]):
        continue
    
    new_lines.append(line)

# Clean up formatting
content = ''.join(new_lines)
content = re.sub(r',\s*,', ',', content)
content = re.sub(r'\[\s*,', '[', content)
content = re.sub(r',\s*\]', ']', content)
content = re.sub(r',\s*\}', '}', content)

with open('app.py', 'w') as f:
    f.write(content)

removed = len(lines) - len(new_lines)
print(f"✅ app.py cleaned ({removed} lines removed)")
ENDPYTHON2

echo ""

#═══════════════════════════════════════════════════════════════════
# PHASE 3: VERIFICATION
#═══════════════════════════════════════════════════════════════════
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}${BOLD} PHASE 3: Verification${NC}"
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Count scanners
SCANNER_COUNT=$(python3 -c "
import re
with open('services/stripe_payment.py', 'r') as f:
    content = f.read()
    match = re.search(r'SCAN_PRICES\s*=\s*\{([^}]+)\}', content, re.DOTALL)
    if match:
        print(len(re.findall(r'\"[^\"]+\"\s*:\s*\d+', match.group(1))))
    else:
        print(0)
")

echo "📊 Scanner count: $SCANNER_COUNT (expected: 16)"

# Check for blob
BLOB_CHECK=$(grep -in "blob" app.py | grep -i "scan\|document\|📄\|blobscanner" || echo "")

if [ -n "$BLOB_CHECK" ]; then
    echo -e "${RED}❌ Blob references found:${NC}"
    echo "$BLOB_CHECK"
    exit 1
else
    echo -e "${GREEN}✅ Blob references removed${NC}"
fi

if [ "$SCANNER_COUNT" -ne 16 ]; then
    echo -e "${RED}❌ Scanner count error: got $SCANNER_COUNT${NC}"
    exit 1
else
    echo -e "${GREEN}✅ Exactly 16 scanners confirmed${NC}"
fi

echo ""

#═══════════════════════════════════════════════════════════════════
# PHASE 4: DOCKER REBUILD
#═══════════════════════════════════════════════════════════════════
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}${BOLD} PHASE 4: Docker Rebuild (Cache-Busted)${NC}"
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Find docker-compose
COMPOSE=""
for f in docker-compose.yml docker-compose.yaml ../docker-compose.yml; do
    [ -f "$f" ] && COMPOSE="$f" && break
done

if [ -z "$COMPOSE" ]; then
    echo -e "${RED}❌ docker-compose.yml not found${NC}"
    exit 1
fi

echo "📄 Compose file: $COMPOSE"

# Export environment variables
export $(grep -v '^#' "$ENV_FILE" | xargs)

# Determine docker-compose command
if command -v docker-compose &>/dev/null; then
    DC="docker-compose"
elif docker compose version &>/dev/null 2>&1; then
    DC="docker compose"
else
    echo -e "${RED}❌ Neither docker-compose nor docker compose found${NC}"
    exit 1
fi

# Stop containers
echo "🛑 Stopping containers..."
$DC -f "$COMPOSE" down 2>/dev/null || true

# Clear build cache
echo "🗑️  Clearing build cache..."
docker builder prune -f 2>/dev/null || true

# Rebuild without cache
echo "🔨 Rebuilding (--no-cache)..."
$DC -f "$COMPOSE" build --no-cache

# Start containers
echo "🚀 Starting containers..."
$DC -f "$COMPOSE" up -d

# Wait for startup
echo "⏳ Waiting 30 seconds for services..."
sleep 30

# Show status
echo ""
echo "📊 Container Status:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | head -10

echo ""

#═══════════════════════════════════════════════════════════════════
# PHASE 5: FINAL CHECK
#═══════════════════════════════════════════════════════════════════
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}${BOLD} PHASE 5: Final Verification${NC}"
echo -e "${BLUE}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "🌐 Testing web server..."
sleep 5
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000 2>/dev/null || echo "000")

if [ "$HTTP_CODE" = "200" ]; then
    echo -e "${GREEN}✅ Web server online (HTTP $HTTP_CODE)${NC}"
else
    echo -e "${YELLOW}⚠️  Web server: HTTP $HTTP_CODE (may still be starting)${NC}"
fi

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  ${BOLD}✅ FIX COMPLETE - ALL SYSTEMS UPDATED${NC}${GREEN}                        ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Summary:"
echo "  ✅ STRIPE_SECRET_KEY configured and loaded"
echo "  ✅ Blob Scan completely removed"
echo "  ✅ Exactly 16 scanners active"
echo "  ✅ Docker rebuilt with fresh cache"
echo "  ✅ All containers restarted"
echo ""
echo -e "${CYAN}${BOLD}Next Steps:${NC}"
echo ""
echo "1️⃣  Test payment page:"
echo "   ${CYAN}https://dataguardianpro.nl/payment_test_ideal${NC}"
echo ""
echo "2️⃣  Hard refresh your browser:"
echo "   Press ${BOLD}Ctrl+Shift+R${NC} (or ${BOLD}Cmd+Shift+R${NC} on Mac)"
echo ""
echo "3️⃣  Verify scanner list shows exactly 16 items (NO Blob Scan)"
echo ""
echo "4️⃣  Check logs if needed:"
echo "   ${CYAN}docker logs dataguardian-pro${NC}"
echo ""
echo -e "${GREEN}Done! Your production server is updated.${NC}"
echo ""
